#pragma once

#include <Windows.h>
#include <dwmapi.h>
#include <WinUser.h>
#include <string>
#include <iostream>
#include <vector>
#include <stdio.h>
#include <array>
#include <xmmintrin.h>
#include <emmintrin.h>
#include <iostream>
#include <winnt.h>
#include <codecvt>
#include <d2d1.h>
#include <variant>
#include <conio.h>
#include <d3d9.h>
#include <d3dx9.h>
#include <d3dx9math.h>
#include "Math.hpp"
#include <thread>
#include <fstream> 
#include <mutex>